Description: >
    This template deploys an Application Load Balancer that exposes our various ECS services.
    We create them it a seperate nested template, so it can be referenced by all of the other nested templates.

Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String

    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the Applicaion Load Balancer should be deployed to

    Subnets:
        Description: Choose which subnets the Applicaion Load Balancer should be deployed to
        Type: List<AWS::EC2::Subnet::Id>

    SecurityGroup:
        Description: Select the Security Group to apply to the Applicaion Load Balancer
        Type: AWS::EC2::SecurityGroup::Id

    CertificateArn:
        Description: The ARN of aws certificate that will be used in LoadBalancer
        Type: String
        Default: arn:aws:acm:us-west-2:202279780353:certificate/a3019aa0-1233-4fa8-b0a6-3d06e2bc4443


Resources:

    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Ref EnvironmentName
            Subnets: !Ref Subnets
            SecurityGroups:
                - !Ref SecurityGroup
            Tags:
                - Key: Name
                  Value: !Ref EnvironmentName

    HttpsLoadBalancerListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            Certificates:
                - CertificateArn: !Ref CertificateArn
            LoadBalancerArn: !Ref LoadBalancer
            Port: 443
            Protocol: HTTPS
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref DefaultTargetGroup

    HttpLoadBalancerListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            Port: 80
            Protocol: HTTP
            DefaultActions:
                - Type: forward
                  TargetGroupArn: !Ref DefaultTargetGroup

    # We define a default target group here, as this is a mandatory Parameters
    # when creating an Application Load Balancer Listener. This is not used, instead
    # a target group is created per-service in each service template (../services/*)
    DefaultTargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Sub ${EnvironmentName}-default-2
            VpcId: !Ref VPC
            Port: 8000
            Protocol: HTTP

Outputs:

    LoadBalancer:
        Description: A reference to the Application Load Balancer
        Value: !Ref LoadBalancer

    LoadBalancerUrl:
        Description: The URL of the ALB
        Value: !GetAtt LoadBalancer.DNSName

    HttpListener:
        Description: A reference to a port 80 listener
        Value: !Ref HttpLoadBalancerListener

    HttpsListener:
        Description: A reference to a port 443 listener
        Value: !Ref HttpsLoadBalancerListener

    FlowerListener:
        Description: A reference to a port 5555 listener
        Value: !Ref FlowerLoadBalancerListener

    SonarqubeListener:
        Description: A reference to a port 9000 listener
        Value: !Ref SonarqubeLoadBalancerListener
